CREATE TABLE COURSES (
  course_id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE GROUPS (
  group_id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE STUDENTS (
  student_id SERIAL PRIMARY KEY,
  group_id INTEGER REFERENCES GROUPS (group_id),
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL
);

CREATE TABLE ATTENDANCEOFCOURSES (
  student_id INTEGER NOT NULL,
  course_id INTEGER NOT NULL,
  PRIMARY KEY (student_id, course_id),
  FOREIGN KEY (student_id) REFERENCES STUDENTS (student_id),
  FOREIGN KEY (course_id) REFERENCES COURSES (course_id)
);

DROP TABLE ATTENDANCEOFCOURSES;
DROP TABLE STUDENTS;
DROP TABLE COURSES;
DROP TABLE GROUPS;